TASK_STATE_FAILED = -1
TASK_STATE_COMPLETE = 1
TASK_STATE_PROCESSING = 4

VOICE_NAME_LIST = [
    "wuu-CN-XiaotongNeural",
    "wuu-CN-YunzheNeural",
    "yue-CN-XiaoMinNeural",
    "yue-CN-YunSongNeural",
    "zh-CN-XiaochenMultilingualNeural",
    "zh-CN-XiaochenNeural",
    "zh-CN-XiaohanNeural",
    "zh-CN-XiaomengNeural",
    "zh-CN-XiaomoNeural",
    "zh-CN-XiaoqiuNeural",
    "zh-CN-XiaorouNeural",
    "zh-CN-XiaoruiNeural",
    "zh-CN-XiaoshuangNeural",
    "zh-CN-XiaoxiaoDialectsNeural",
    "zh-CN-XiaoxiaoMultilingualNeural",
    "zh-CN-XiaoxiaoNeural",
    "zh-CN-XiaoyanNeural",
    "zh-CN-XiaoyiNeural"
    "zh-CN-XiaoyouNeural",
    "zh-CN-XiaoyuMultilingualNeural",
    "zh-CN-XiaozhenNeural",
    "zh-CN-YunfengNeural",
    "zh-CN-YunhaoNeural",
    "zh-CN-YunjianNeural",
    "zh-CN-YunjieNeural",
    "zh-CN-YunxiNeural",
    "zh-CN-YunxiaNeural",
    "zh-CN-YunxiaoMultilingualNeural",
    "zh-CN-YunyangNeural",
    "zh-CN-YunyeNeural",
    "zh-CN-YunyiMultilingualNeural",
    "zh-CN-YunzeNeural",
    "zh-CN-henan-YundengNeural",
    "zh-CN-liaoning-XiaobeiNeural",
    "zh-CN-shaanxi-XiaoniNeural",
    "zh-CN-shandong-YunxiangNeural",
    "zh-CN-sichuan-YunxiNeural",
    "zh-HK-HiuGaaiNeural",
    "zh-HK-HiuMaanNeural",
    "zh-HK-WanLungNeural",
    "zh-TW-HsiaoChenNeural",
    "zh-TW-HsiaoYuNeural",
    "zh-TW-YunJheNeural"
]
